# this is a scenario file in TOML

[scenario]
name = "My scenario for bitcoin net"
description = """\
                This is an example scenario \
                It will describe in a sequential order some tasks \
                which will be executed by the network.\
                """
date = 2025-06-10T13:08:00
author = "Pallandos"

[config]
default_node = "node_1"
default_wait = 2
timeout = 2

# ===== steps =====
[steps.step1]
name = "Create wallet"
action = "create_wallet"
node = "node_1"
args.wallet_name = "wallet1"
wait_after = 4

[steps.step2]
name = "Create address"
action = "create_address"
node = "node_1"
args.store_result = "ADDRESS1"
wait_after = 4

[steps.step3]
name = "Mine some blocks"
action = "mine"
node = "node_1"
args.amount = 101
args.address = "${ADDRESS1}"


[steps.step4]
name = "Create wallet"
action = "create_wallet"
node = "node_2"
args.wallet_name = "wallet2"
wait_after = 4

[steps.step5]
name = "Create address"
action = "create_address"
node = "node_2"
args.store_result = "ADDRESS2"
wait_after = 4

[steps.step6]
name = "print balance"
action = "cmd"
node = "node_2"
args.cmd = "getbalance"
print = true

[steps.step7]
name = "send coins"
action = "send_to"
node = "node_1"
args.amount = "10"
args.to = "${ADDRESS2}"

[steps.step8]
name = "mine to confirm"
action = "mine"
node = "node_1"
args.amount = 1
args.address = "${ADDRESS1}"

[steps.step9]
name = "print balance"
action = "cmd"
node = "node_2"
args.cmd = "getbalance"
print = true