services:

  node_1:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: node_1
    environment: 
      RPC_USER: user
      RPC_PASS: password
    command:
    - -rpcallowip=0.0.0.0/0
    - -rpcbind=0.0.0.0
    - -rpcuser=user
    - -rpcpassword=password
    - -maxconnections=128
    - -listen=1
    - -rpcport=18443
    - -port=18444
    - -addnode=node_5:18452 
    - -debug=tx
    - -debug=mempool
    - -conf=/run/configs/bitcoin_conf
    ports:
    - "18443:18443"
    - "18444:18444"
    networks:
    - bitcoin-net
    configs:
    - source: bitcoin_conf
      target: /run/configs/bitcoin_conf
  node_2:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: node_2
    environment: 
      RPC_USER: user
      RPC_PASS: password
    command:
    - -rpcallowip=0.0.0.0/0
    - -rpcbind=0.0.0.0
    - -rpcuser=user
    - -rpcpassword=password
    - -maxconnections=128
    - -listen=1
    - -rpcport=18445
    - -port=18446
    - -addnode=node_5:18452 
    - -addnode=node_3:18448 
    - -addnode=node_4:18450 
    - -debug=tx
    - -debug=mempool
    - -conf=/run/configs/bitcoin_conf
    ports:
    - "18445:18445"
    - "18446:18446"
    networks:
    - bitcoin-net
    configs:
    - source: bitcoin_conf
      target: /run/configs/bitcoin_conf
  node_3:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: node_3
    environment: 
      RPC_USER: user
      RPC_PASS: password
    command:
    - -rpcallowip=0.0.0.0/0
    - -rpcbind=0.0.0.0
    - -rpcuser=user
    - -rpcpassword=password
    - -maxconnections=128
    - -listen=1
    - -rpcport=18447
    - -port=18448
    - -addnode=node_5:18452 
    - -addnode=node_1:18444 
    - -debug=tx
    - -debug=mempool
    - -conf=/run/configs/bitcoin_conf
    ports:
    - "18447:18447"
    - "18448:18448"
    networks:
    - bitcoin-net
    configs:
    - source: bitcoin_conf
      target: /run/configs/bitcoin_conf
  node_4:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: node_4
    environment: 
      RPC_USER: user
      RPC_PASS: password
    command:
    - -rpcallowip=0.0.0.0/0
    - -rpcbind=0.0.0.0
    - -rpcuser=user
    - -rpcpassword=password
    - -maxconnections=128
    - -listen=1
    - -rpcport=18449
    - -port=18450
    - -addnode=node_1:18444 
    - -debug=tx
    - -debug=mempool
    - -conf=/run/configs/bitcoin_conf
    ports:
    - "18449:18449"
    - "18450:18450"
    networks:
    - bitcoin-net
    configs:
    - source: bitcoin_conf
      target: /run/configs/bitcoin_conf
  node_5:
    image: ruimarinho/bitcoin-core:24.0.1
    container_name: node_5
    environment: 
      RPC_USER: user
      RPC_PASS: password
    command:
    - -rpcallowip=0.0.0.0/0
    - -rpcbind=0.0.0.0
    - -rpcuser=user
    - -rpcpassword=password
    - -maxconnections=128
    - -listen=1
    - -rpcport=18451
    - -port=18452
    - -addnode=node_2:18446 
    - -addnode=node_3:18448 
    - -debug=tx
    - -debug=mempool
    - -conf=/run/configs/bitcoin_conf
    ports:
    - "18451:18451"
    - "18452:18452"
    networks:
    - bitcoin-net
    configs:
    - source: bitcoin_conf
      target: /run/configs/bitcoin_conf

networks:
  bitcoin-net:
    driver: bridge
    attachable: true
configs:
  bitcoin_conf:
    file: ./bitcoin_conf.conf

